### ISSUE TITLE
Initial config for care-giver program

### ISSUE THREAD

**Issue by chingalo** [chingalo/pact-swazi-commcare#40]
- config for caregiver programs
     - config profile info with links form(s) without attributes values mapping
     - config program stages with links form(s) without data values mapping
- Expose config for caregiver program
- Adding initial set up for caregiver helper with imports

**Comment by chingalo** [comment]
Hello @ebrahimhassan110 any updates on this

**Comment by ebrahimhassan110** [comment]
Sir, I have done initial configurations and mapping program stages with form names in the file. But I still have a problem in 2  program stages

**Comment by ebrahimhassan110** [comment]
Initial configurations done
